version: '3.9'

services:
  postgres:
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend/src:/app/src
    environment:
      NODE_ENV: development
    command: npm run start:dev

  frontend:
    image: node:20-alpine
    container_name: hr-frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0
    environment:
      VITE_API_URL: http://localhost:3000
